#!/usr/bin/env python3
"""
Build an expanded feature CSV with rolling stats for multiple windows
for both team and opponent metrics.

Input:
  - espn_team_game_features.csv (generated by your existing ESPN pipeline)

Outputs:
  - ml/features_all_windows.csv  (expanded for all lookbacks)
"""

from __future__ import annotations

import pandas as pd
import numpy as np
from pathlib import Path
from typing import Sequence

from rolling_features import RollingConfig, add_unweighted_rollups

# windows to generate
LOOKBACK_WINDOWS = [3, 4, 5, 6, 7, 10, 12]

# base metrics (team stats) observed in raw feature CSV
BASE_METRICS = [
    "ortg", "drtg", "netrtg", "pace", "efg", "tov_pct",
    "orb_pct", "drb_pct", "ftr", "3par"
]

# global paths
IN_CSV = Path("espn_team_game_features.csv")
OUT_CSV = Path("ml/features_all_windows.csv")


def _generate_windows(
    df: pd.DataFrame,
    metrics: Sequence[str],
    group_col: str = "team_id",
) -> pd.DataFrame:
    """
    Loop over LOOKBACK_WINDOWS and add rolling stats for each metric.
    This returns the augmented DataFrame.
    """
    out = df.copy()

    for w in LOOKBACK_WINDOWS:
        prefix = f"{w}_pre"
        cfg = RollingConfig(
            group_cols=(group_col,),
            order_col="game_datetime_utc",
            window=w,
            prefix=f"{prefix}_",
        )

        print(f"[INFO] Adding rolling window={w} for {group_col}")
        out = add_unweighted_rollups(
            out,
            metrics=metrics,
            cfg=cfg,
            include_minmax=True,
            include_iqr=True,
            include_percentiles=(0.20, 0.80),
            include_slope=True,
            include_shift=True,
        )

    return out


def main() -> None:
    if not IN_CSV.exists():
        raise FileNotFoundError(f"Input CSV not found: {IN_CSV}")

    print(f"[INFO] Loading raw ESPN features from {IN_CSV}")
    df = pd.read_csv(IN_CSV)

    # sort for stability
    df = df.sort_values(["team_id", "game_datetime_utc", "event_id", "home_away"]).reset_index(drop=True)

    # generate rolling windows for team stats
    df = _generate_windows(df, BASE_METRICS, group_col="team_id")

    # generate rolling for opponent stats
    opp_metrics = [f"opp_{m}" for m in BASE_METRICS]
    df = _generate_windows(df, opp_metrics, group_col="opp_team_id")

    # write out expanded features
    OUT_CSV.parent.mkdir(parents=True, exist_ok=True)
    print(f"[INFO] Writing expanded ML features to {OUT_CSV}")
    df.to_csv(OUT_CSV, index=False)

    print(f"[INFO] Done. Total rows={len(df)} cols={len(df.columns)}")


if __name__ == "__main__":
    main()
